### ISSUE TITLE
Object property order not maintained

### ISSUE THREAD

**Issue by smeijer** [apollographql/apollo-engine-js#180] opened 2018-04-26 12:18 UTC
Although it is not a javascript standard, object property order is usually maintained. When I return an object `{ a: 1, c: 2, b: 3 }` from my resolver, the client will receive this object with the same property order `{ a: 1, c: 2, b: 3 }`.

But, it turned out, Apollo Engine changes this behavior. Apollo with Apollo Engine in between, modifies the object to have the keys sorted alphabetically: `{ a: 1, b: 3, c: 2 }`.

I am aware that we should not depend on object property order, but still; this resulted in a small bug on my side. So a written warning about this subject (in the readme for example) should be most welcome.

I believe it would even better if Engine just forwarded the orriginal data, instead of the modified version (which I expect you need for caching).

---

```
apollo                   with engine

server sends -> 
{                        {
  a: 1,                    a: 1,
  c: 2,                    c: 2,
  b: 3,                    b: 3,
}                        }

client receives ->
{                        {
  a: 1,                    a: 1,               
  c: 2,                    b: 3,
  b: 3,                    c: 2,
}                        }
```

**Comment by glasser** [comment] 2018-04-26 19:15
Due to the implementation we use, we are unlikely to change how JSON serialization in the Engine proxy works. I agree that it might be worth documenting this somewhere, though I'm not sure where.

**Comment by sbrichardson** [comment] 2018-06-21 18:39
I don't think obj property order should be relied upon in logic, nor query param order, since by design in JS it's not guaranteed. I know some people use it to detect if an object (or route) has changed, but using a different normalization algorithm is a simple fix outside of this lib.

**Comment by sbrichardson** [comment] 2018-06-21 18:42
For docs, maybe a faq or misc notes at end of engine docs? To accumulate any knowledge bits until they are enough to be organized? Or just close the issue, and let that be the source for search.

**Comment by sbrichardson** [comment] 2018-07-30 23:49
This isn’t really an issue for me but was looking at related needs. In the source for engine you could potentially convert to a JavaScript map and use array of two element arrays, since a map will maintain order, and stringify. Or if necessary for a client side only need, create an Apollo link (or in result) that converts to a js map by reading an array of keys in context or similar.

http://2ality.com/2015/08/es6-map-json.html

**Comment by danilobuerger** [comment] 2018-12-21 13:15
> GraphQL Objects represent a list of named fields, each of which yield a value of a specific type. Object values should be serialized as ordered maps, where the queried field names (or aliases) are the keys and the result of evaluating the field is the value, ordered by the order in which they appear in the query.

https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md

@glasser It should be documented that engine does not conform to the graphql standard.

**Comment by glasser** [comment] 2018-12-21 16:53
The engine proxy is deprecated and we only suggest it for the specific use cases mentioned at https://www.apollographql.com/docs/references/engine-proxy.html
We hope to reduce that set of use cases in the future.

**Closed by glasser** 2018-12-21 16:53 UTC
