### ISSUE TITLE
Conflict with timber-node package

### ISSUE THREAD

**Issue by owensbla** [apollographql/apollo-engine-js#24] opened 2017-10-26 20:40 UTC
Error when running sidecar package alongside [timber-node](https://github.com/timberio/timber-node):

```js
TypeError: log.split is not a function
    at stripMetadata (/Development/api/node_modules/timber/dist/utils/metadata.js:7:14)
    at WriteStream.toStream.write (/Development/api/node_modules/timber/dist/utils/attach.js:76:159)
    at LineWrapper.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at LineWrapper.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at LineWrapper.Readable.push (_stream_readable.js:211:10)
    at LineWrapper.Transform.push (_stream_transform.js:147:32)
    at LineWrapper.<anonymous> (/Development/api/node_modules/stream-line-wrapper/lib/line-wrapper.js:75:10)
    at Array.forEach (<anonymous>)
    at LineWrapper._transform (/Development/api/node_modules/stream-line-wrapper/lib/line-wrapper.js:74:9)
    at LineWrapper.Transform._read (_stream_transform.js:186:10)
    at LineWrapper.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at LineWrapper.Writable.write (_stream_writable.js:288:11)
    at Socket.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:585:20)
```

Assuming it has to do with timber hijacking `console.log` methods.

**Comment by zionts** [comment] 2017-11-30 22:05
Thanks for writing this in and pointing this out! It looks like this is likely an incompatibility issue, and we'd love to try to support timber-node. It would be really useful if you could provide a reproduction of this issue in the form of a PR that adds timber-node logging as a test case in /test/ and maybe even pinpointing where in the code you thing the bug might lie.

We'd love to support all third party packages – to prioritize, we rely on community feedback to choose where we spend our time. Please 👍 this issue if adding support for timber-node is important to you.

**Comment by zionts** [comment] 2018-02-05 18:52
I think this is resolved by https://github.com/apollographql/apollo-engine-js/pull/114 :) Thanks to @orangecms!

**Closed by zionts** 2018-02-05 18:52 UTC
Labels: upgrade / integration request
