### ISSUE TITLE
Usage with graphiql

### ISSUE THREAD

**Issue by lyzs90** [apollographql/apollo-engine-js#36] opened 2017-11-10 04:38 UTC
I'm running the following middleware: `apollo-engine` -> `graphiqlExpress` -> `graphqlExpress`.

When i execute queries in GraphiQL, the response in the IDE contains the (seemingly correct) data and extension fields, however, i'm seeing no data at all in the Engine dashboard. Anyone know why?

**Comment by sbr464** [comment] 2017-11-10 05:49
Here is most of the code of a working example, if it helps.

**engineConfig.js**

```
const PORT = process.env.PORT || 3001
const APOLLO_ENGINE_API_KEY = process.env.APOLLO_ENGINE_API_KEY
const GQL_ENDPOINT = process.env.GQL_ENDPOINT

export default {
  "engineConfig": {
    "stores": [
      {
        "name": "embeddedCache",
        "inMemory": {
          "cacheSize": 2485760
        }
      }
    ],
    "apiKey": APOLLO_ENGINE_API_KEY,
    "queryCache": {
      "publicFullQueryStore": "embeddedCache",
      "privateFullQueryStore": "embeddedCache"
    },
    "reporting": {
      "maxAttempts": 5,
      "endpointUrl":  "https://engine-report.apollodata.com",
      "debugReports": false
    },
    "logging": {
      "level": "ERROR"   // Engine Proxy logging level. DEBUG, INFO, WARN or ERROR
    }
  },
  "graphqlPort": PORT,  // GraphQL port
  "endpoint": GQL_ENDPOINT,                  // GraphQL endpoint suffix - '/graphql' by default
  "dumpTraffic": false                       // Debug configuration that logs traffic between Proxy and GraphQL server
}

```

**engine.js**

```
import { Engine } from 'apollo-engine'
import engineConfig from './engineConfig'

const engine = new Engine(engineConfig)
export { engine }

```


** main.js ** (inside an async function)

```
  // ...shortened

  await engine.start()
  const app = express()
  app.use(engine.expressMiddleware())
  app.use(cors())
  app.use(compression())

  /****
  * Graphql Routes
  ****/

  app.use('/graphql', json(), graphqlExpress(request => ({
    schema,
    cacheControl: true,
    tracing: true,
    context: {
      request
    }
  })))

  app.use('/graphiql', graphiqlExpress({
    endpointURL: process.env.GQL_ENDPOINT
  }))

  /****
  * Start server
  ****/
  app.listen(process.env.PORT || 3001)

```

**Comment by lyzs90** [comment] 2017-11-10 07:14
thank you, im using sails.js and i realised i was configuring the middleware wrongly. now that's fixed but i've run into another issue:
- if i place Engine above bodyParser, it errors out and this gets logged in the dashboard:
<img width="361" alt="screen shot 2017-11-10 at 3 13 16 pm" src="https://user-images.githubusercontent.com/13202538/32646876-b5faefea-c629-11e7-9f93-68c4126e12d0.png">

- however, if i place it after bodyParser, the request just hangs there and nothing gets reported to the dashboard

**Comment by zionts** [comment] 2017-12-07 22:42
Hi @lyzs90, Sorry for the delay in getting back to you on this. Since we don't have an SLA via Github, the best place to go for Apollo Engine support is https://engine.apollographql.com/support or a direct email (support@apollographql.com). This particular error seems like it might be related to a bug that was fixed in the newer versions of the engineproxy binary (#54 and #60 were as well). I'm going to close this out for now, but definitely reach out to support if you find yourself battling errors again. If you find any problem with the open-source middleware code in this project, then definitely come here and we'll take a look as soon as we can.

**Closed by zionts** 2017-12-07 22:42 UTC

**Comment by mlescaudron** [comment] 2017-12-11 02:32
Hey,

So I have the same problem, no data appear.
I can see the log : 
{ proxy: 
```
   { level: 'debug',
     msg: 'reporting-client - [DEBUG] POST https://engine-report.apollodata.com/api/ss/stats',
     time: '2017-12-11T02:30:12Z' } }
```
But No data appears on apolloEngine.
Here is my engine.js : 
```
import { Engine } from 'apollo-engine'

const engine = new Engine({
  engineConfig: {
    apiKey: process.env.ENGINE_API_KEY,
    logging: {
      level: process.env.NODE_ENV === "production" ? 'INFO' : 'DEBUG'
    }
  },
  graphqlPort: process.env.PORT || 8003,
  endpoint: '/api',
  dumpTraffic: process.env.NODE_ENV === "production" ? false : true,
});

export { engine }

```

**Comment by zionts** [comment] 2017-12-11 19:10
Hi there,
If you're running into a problem where GraphiQL returns the correct data and extensions, yet data isn't appearing in your Engine UI when using your app's non-graphiql endpoint, then the problem is likely an issue in how Engine is configured. The POST to the /stats endpoint is simply a record of the Engine instance's CPU usage, and indicates that Engine is running, but says nothing about the accuracy of the configuration or whether or not traffic is being routed through the Engine Proxy.

If there is no POST to the /traces endpoint after you execute a query, that implies that there is an error in the configuration where traffic from your GraphQL server isn't being properly routed through EngineProxy. The first thing to check is that your `graphqlPort` and `endpoint` variables are accurate, and then consider digging a little deeper into the traffic that your GraphQL server sees to make sure it's receiving requests forwarded through Engine Proxy.
